export interface FrameTheme {
  id: string
  label: string
  emoji: string
  bgColor: string
  accentColor: string
  textColor: string
  subtextColor: string
  photoBorderColor: string
  cornerEmojis: [string, string, string, string] | null
  title: string
  pattern: 'dots' | 'hearts' | 'stars' | 'lines'
}

export const FRAME_THEMES: FrameTheme[] = [
  {
    id: 'sakura',
    label: 'Sakura',
    emoji: '🌸',
    bgColor: '#FFF0F5',
    accentColor: '#F48FB1',
    textColor: '#AD1457',
    subtextColor: '#D81B60',
    photoBorderColor: '#F8BBD0',
    cornerEmojis: ['🌸', '🌸', '🌸', '🌸'],
    title: '🌸 Sakura Booth',
    pattern: 'hearts',
  },
  {
    id: 'ribbon',
    label: 'Ribbon',
    emoji: '🎀',
    bgColor: '#F3E8FF',
    accentColor: '#C084FC',
    textColor: '#7E22CE',
    subtextColor: '#9333EA',
    photoBorderColor: '#D8B4FE',
    cornerEmojis: ['🎀', '🎀', '🎀', '🎀'],
    title: '🎀 Ribbon Cutie',
    pattern: 'dots',
  },
  {
    id: 'sparkle',
    label: 'Sparkle',
    emoji: '✨',
    bgColor: '#2D1B4E',
    accentColor: '#FBBF24',
    textColor: '#FDE68A',
    subtextColor: '#FCD34D',
    photoBorderColor: '#FBBF24',
    cornerEmojis: ['✨', '⭐', '✨', '⭐'],
    title: '✨ Sparkle Night',
    pattern: 'stars',
  },
  {
    id: 'classic',
    label: 'Classic',
    emoji: '🖤',
    bgColor: '#FFFFFF',
    accentColor: '#1F1F1F',
    textColor: '#1F1F1F',
    subtextColor: '#525252',
    photoBorderColor: '#E0E0E0',
    cornerEmojis: null,
    title: 'Photobooth',
    pattern: 'lines',
  },
  {
    id: 'ocean',
    label: 'Ocean',
    emoji: '🌊',
    bgColor: '#E0F7FA',
    accentColor: '#4FC3F7',
    textColor: '#0277BD',
    subtextColor: '#0288D1',
    photoBorderColor: '#81D4FA',
    cornerEmojis: ['🌊', '🐚', '🌊', '🐚'],
    title: '🌊 Ocean Blue',
    pattern: 'dots',
  },
  {
    id: 'sunset',
    label: 'Sunset',
    emoji: '🌅',
    bgColor: '#FFF3E0',
    accentColor: '#FF8A65',
    textColor: '#BF360C',
    subtextColor: '#D84315',
    photoBorderColor: '#FFAB91',
    cornerEmojis: ['🌅', '🌤️', '🌅', '🌤️'],
    title: '🌅 Sunset Glow',
    pattern: 'dots',
  },
  {
    id: 'mint',
    label: 'Mint',
    emoji: '🌿',
    bgColor: '#E8F5E9',
    accentColor: '#81C784',
    textColor: '#2E7D32',
    subtextColor: '#388E3C',
    photoBorderColor: '#A5D6A7',
    cornerEmojis: ['🌿', '🍃', '🌿', '🍃'],
    title: '🌿 Mint Segar',
    pattern: 'hearts',
  },
  {
    id: 'midnight',
    label: 'Midnight',
    emoji: '🌙',
    bgColor: '#1A237E',
    accentColor: '#90A4AE',
    textColor: '#E3F2FD',
    subtextColor: '#BBDEFB',
    photoBorderColor: '#7986CB',
    cornerEmojis: ['🌙', '⭐', '🌙', '⭐'],
    title: '🌙 Midnight Sky',
    pattern: 'stars',
  },
  {
    id: 'cotton-candy',
    label: 'Cotton Candy',
    emoji: '🍭',
    bgColor: '#FCE4EC',
    accentColor: '#81D4FA',
    textColor: '#AD1457',
    subtextColor: '#D81B60',
    photoBorderColor: '#F8BBD0',
    cornerEmojis: ['🍭', '🍬', '🍭', '🍬'],
    title: '🍭 Cotton Candy',
    pattern: 'dots',
  },
  {
    id: 'retro',
    label: 'Retro',
    emoji: '📷',
    bgColor: '#FFF8E1',
    accentColor: '#A1887F',
    textColor: '#4E342E',
    subtextColor: '#6D4C41',
    photoBorderColor: '#D7CCC8',
    cornerEmojis: ['📷', '🎞️', '📷', '🎞️'],
    title: '📷 Retro Booth',
    pattern: 'lines',
  },
  {
    id: 'tropical',
    label: 'Tropical',
    emoji: '🌴',
    bgColor: '#FFF9C4',
    accentColor: '#66BB6A',
    textColor: '#1B5E20',
    subtextColor: '#2E7D32',
    photoBorderColor: '#C5E1A5',
    cornerEmojis: ['🌴', '🌺', '🌴', '🌺'],
    title: '🌴 Tropical Vibes',
    pattern: 'hearts',
  },
  {
    id: 'golden',
    label: 'Golden',
    emoji: '🌟',
    bgColor: '#FFF8E1',
    accentColor: '#FFD54F',
    textColor: '#E65100',
    subtextColor: '#F57F17',
    photoBorderColor: '#FFE082',
    cornerEmojis: ['🌟', '✨', '🌟', '✨'],
    title: '🌟 Golden Hour',
    pattern: 'stars',
  },
]

export const DEFAULT_THEME = FRAME_THEMES[1]

export function getThemeById(id: string): FrameTheme {
  return FRAME_THEMES.find((t) => t.id === id) ?? DEFAULT_THEME
}
